language: node_js
node_js:
  - "4.0"
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/eacdc382fb52d269de7c
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
