language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"
before_install: npm install react
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/eacdc382fb52d269de7c
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
